### ISSUE TITLE
Add a GitHub Pages branch

### ISSUE THREAD

**Issue by Quuxplusone** [catseye/Flobnar#3]
If you go into this project's settings and mark `master` as your GitHub Pages branch, then navigating to https://catseye.github.io/Flobnar/demo/flobnar.html should Just Work, eliminating the need for people to download the HTML demo in order to see it.

**Comment by Quuxplusone** [comment]
Hm, no, you'd also have to check-in a pre-built copy of `flobnar.js` to the repository in order for it to really Just Work. But I'd like to see a copy of `flobnar.js` anyway, because building `flobnar.js` requires `hastec` which requires `ghc` which [requires a POSIX-compliant `nm`](https://gitlab.haskell.org/ghc/ghc/issues/11744) which requires not-being-on-OSX as far as I can tell. :(

**Comment by cpressey** [comment]
This might be the solution to the root problem here: https://catseye.tc/installation/Flobnar .  You can see a copy of `flobnar.js` by reading the source of that page.  That page has been there for a little while; I've been meaning to draw attention to it, but I've been fairly busy.

Regarding some of the other points:
* I have my doubts about committing generated files to version control
* I avoid using github pages because I already have a website, and it duplicates things
* Shame that you can't build `hastec` on Mac, especially since Haste kind of sells itself as being easy to build (relative to other Haskell-to-X compilers, anyway).  Have you tried using a `ghc` binary from a package manager, or a Docker image?  I can easily imagine that that's not enough, though, too, since `hastec` seems to be based on `ghc` in a deep way.
